services:
  metrics:
    build: 
      context: .
      dockerfile: .docker/discord_metrics/Dockerfile
    environment:
      - DISCORD_GUILDS=${DISCORD_GUILDS}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}