services:
  otel-collector:
      build:
        context: .docker/otel
        dockerfile: Dockerfile
      restart: always
      environment:
        OTELCOL_ARGS: ""
      volumes:
        - ./otel-config.yaml:/etc/otel-collector-config.yaml
      ports:
        - "8889:8889"   # Prometheus exporter metrics
        - "4317:4317"   # OTLP gRPC receiver
  
  prometheus:
    build:
      context: .docker/prometheus
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"