// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/murasame29/discord_metrics/builder

go 1.21

require (
	go.opentelemetry.io/collector/confmap/converter/expandconverter v0.100.0
	go.opentelemetry.io/collector/confmap/provider/envprovider v0.100.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v0.100.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v0.100.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v0.100.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v0.100.0
	go.opentelemetry.io/collector/receiver/otlpreceiver v0.100.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.100.0
	github.com/murasame29/discord_metrics/receiver v0.0.0
	go.opentelemetry.io/collector/processor/batchprocessor v0.100.0
	go.opentelemetry.io/collector/otelcol v0.100.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)




replace github.com/murasame29/discord_metrics/receiver => ./receiver
