receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  discord:
    token: $DISCORD_TOKEN
  
processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443" 
    headers:
      x-honeycomb-team: $HONEYCOMB_TOKEN 
  debug:
    verbosity: debug      

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - discord
      exporters:
        - otlp
        - debug