receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  discord:
    token: $DISCORD_TOKEN
    guildID: $DISCORD_GUILDS

processors:
  batch:

exporters:
  otlphttp:
    endpoint: https://otlp.nr-data.net
    headers:
      api-key: $NEW_RELIC_LICENSE_KEY

  debug:

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - discord
      exporters:
        - otlphttp
        - debug