receivers:
  otlp:
    protocols:
      grpc:

  discord:
    token: USE_YOUR_TOKEN_HERE

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - discord 
      processors:
        - batch
      exporters: 
        - prometheus