// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testConfigCollection int

const (
	testSetDefault testConfigCollection = iota
	testSetAll
	testSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name      string
		configSet testConfigCollection
	}{
		{
			name:      "default",
			configSet: testSetDefault,
		},
		{
			name:      "all_set",
			configSet: testSetAll,
		},
		{
			name:      "none_set",
			configSet: testSetNone,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopCreateSettings()
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, test.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordDiscordJoinCountDataPoint(ts, 1, "discord.guild.id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordDiscordLeaveCountDataPoint(ts, 1, "discord.guild.id-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordDiscordMessagesCountDataPoint(ts, 1, "discord.category.id-val", "discord.category.name-val", "discord.channel.id-val", "discord.channel.name-val", "discord.messageby.id-val", "discord.messageby.name-val")

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if test.configSet == testSetNone {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if test.configSet == testSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if test.configSet == testSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "discord.join.count":
					assert.False(t, validatedMetrics["discord.join.count"], "Found a duplicate in the metrics slice: discord.join.count")
					validatedMetrics["discord.join.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "The number of join guild", ms.At(i).Description())
					assert.Equal(t, "{join}", ms.At(i).Unit())
					assert.Equal(t, true, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("discord.guild.id")
					assert.True(t, ok)
					assert.EqualValues(t, "discord.guild.id-val", attrVal.Str())
				case "discord.leave.count":
					assert.False(t, validatedMetrics["discord.leave.count"], "Found a duplicate in the metrics slice: discord.leave.count")
					validatedMetrics["discord.leave.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "The number of laeve guild", ms.At(i).Description())
					assert.Equal(t, "{leave}", ms.At(i).Unit())
					assert.Equal(t, true, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("discord.guild.id")
					assert.True(t, ok)
					assert.EqualValues(t, "discord.guild.id-val", attrVal.Str())
				case "discord.messages.count":
					assert.False(t, validatedMetrics["discord.messages.count"], "Found a duplicate in the metrics slice: discord.messages.count")
					validatedMetrics["discord.messages.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "The number of messages sent to the guild", ms.At(i).Description())
					assert.Equal(t, "{messages}", ms.At(i).Unit())
					assert.Equal(t, true, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("discord.category.id")
					assert.True(t, ok)
					assert.EqualValues(t, "discord.category.id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("discord.category.name")
					assert.True(t, ok)
					assert.EqualValues(t, "discord.category.name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("discord.channel.id")
					assert.True(t, ok)
					assert.EqualValues(t, "discord.channel.id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("discord.channel.name")
					assert.True(t, ok)
					assert.EqualValues(t, "discord.channel.name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("discord.messageby.id")
					assert.True(t, ok)
					assert.EqualValues(t, "discord.messageby.id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("discord.messageby.name")
					assert.True(t, ok)
					assert.EqualValues(t, "discord.messageby.name-val", attrVal.Str())
				}
			}
		})
	}
}
