// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/confmap"

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for discord metrics.
type MetricsConfig struct {
	DiscordMetricsJoinCount       MetricConfig `mapstructure:"discord-metrics.join.count"`
	DiscordMetricsLeaveCount      MetricConfig `mapstructure:"discord-metrics.leave.count"`
	DiscordMetricsMessagesCount   MetricConfig `mapstructure:"discord-metrics.messages.count"`
	DiscordMetricsVcEventCount    MetricConfig `mapstructure:"discord-metrics.vc-event.count"`
	DiscordMetricsVcActiveMembers MetricConfig `mapstructure:"discord_metrics.vc_active_members"`
	DiscordMetricsVcDuration      MetricConfig `mapstructure:"discord_metrics.vc_duration"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		DiscordMetricsJoinCount: MetricConfig{
			Enabled: true,
		},
		DiscordMetricsLeaveCount: MetricConfig{
			Enabled: true,
		},
		DiscordMetricsMessagesCount: MetricConfig{
			Enabled: true,
		},
		DiscordMetricsVcEventCount: MetricConfig{
			Enabled: true,
		},
		DiscordMetricsVcActiveMembers: MetricConfig{
			Enabled: true,
		},
		DiscordMetricsVcDuration: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for discord metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
